- name: Create app directory
  file:
    path: /home/ubuntu/app
    state: directory
    mode: '0755'

- name: Copy app.js to the directory
  copy:
    src: app.js
    dest: /home/ubuntu/app/app.js

- name: Run app with PM2
  shell: |
    cd /home/ubuntu/app
    pm2 start app.js
