- name: Install Node.js LTS
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs

- name: Switch Node.js to 13.8.0 with n
  become: true
  shell: |
    sudo npm install --global n
    sudo n 13.8.0

- name: Installing PM2 Process Manager
  become: true
  npm:
    global: true
    name: pm2
    state: latest
